"use client";
import {useState} from "react";
import {Bell,BookOpen,Box,CalendarDays,ChevronRight,ClipboardList,LayoutDashboard,LogOut,MessageSquare,PackageCheck,Plus,Search,Settings,ShoppingBag,Users,Video,Wrench} from "lucide-react";

const nav=[['overview','数据总览',LayoutDashboard],['notices','消息发布',Bell],['repairs','报修管理',Wrench],['events','赛事管理',CalendarDays],['products','商品管理',Box],['orders','订单管理',ShoppingBag],['courses','课程管理',BookOpen],['students','学员账号',Users],['community','社区审核',Video],['settings','系统设置',Settings]] as const;
type View=typeof nav[number][0];
const rows={
 repairs:[['BX20260827003','林小飞','右前电机不转','检测中','16:40'],['BX20260827002','陈一航','保护罩断裂','待确认','14:12'],['BX20260826009','张可欣','遥控器无法连接','已收件','昨天']],
 events:[['SBS 秋季青少年 3v3 对抗赛','9月12日','48 / 60','报名中'],['学员飞手等级考核','9月20日','22 / 30','即将截止'],['会员月度积分赛','10月3日','31 / 48','报名中']],
 products:[['训练级 20cm 球机套装','整机','¥699','36','销售中'],['2S 550mAh 电池 ×3','电池','¥129','8','库存预警'],['AIO 飞控电调一体板','飞控','¥239','18','销售中'],['球形保护罩维修材料包','材料','¥89','52','销售中']],
 orders:[['SO20260827018','王子墨','竞赛级高响应球机','¥1,299','待发货'],['SO20260827017','周乐乐','电池与充电套装','¥297','已完成'],['SO20260826081','林小飞','保护罩维修材料包','¥89','待取货']],
 courses:[['零基础体验课','2 小时','36','¥99','招生中'],['飞手系统班','6 节课','82','¥699','招生中'],['战队竞技班','10 节课','24','¥1,899','名额紧张']],
 students:[['SBS0086','林小飞','周六进阶班','2 门课程','正常'],['SBS0102','陈一航','周日基础班','1 门课程','正常'],['SBS0068','王子墨','竞赛集训班','4 门课程','正常']],
 community:[['林小飞','飞行视频 · 00:26','18 分钟前','待审核'],['张可欣','装备照片 · 1 张','1 小时前','已通过'],['王子墨','赛事照片 · 3 张','昨天','已通过']]
};

export default function Admin(){const [view,setView]=useState<View>('overview'),[toast,setToast]=useState('');const say=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),1800)};const item=nav.find(n=>n[0]===view)!;return <main className="admin-shell"><aside className="admin-side"><div className="admin-brand"><img src="/sbs-icon.png"/><div><b>SBS 管理中心</b><span>机构运营后台</span></div></div><nav>{nav.map(([id,label,I])=><button key={id} className={view===id?'on':''} onClick={()=>setView(id)}><I/><span>{label}</span>{id==='repairs'&&<em>3</em>}</button>)}</nav><a href="/"><LogOut/>返回学员端</a></aside><section className="admin-main"><header><div><small>INSTITUTION ADMIN</small><h1>{item[1]}</h1></div><div className="admin-account"><span>SBS 机构管理员</span><b>管</b></div></header><div className="admin-content">{view==='overview'?<Overview go={setView}/>:view==='notices'?<Notices say={say}/>:view==='settings'?<SettingsPage say={say}/>:<Manager view={view} say={say}/>}</div></section>{toast&&<div className="admin-toast">{toast}</div>}</main>}

function Overview({go}:{go:(v:View)=>void}){return <div className="admin-stack"><section className="admin-welcome"><div><span>2026年8月27日 · 星期四</span><h2>晚上好，今日运营情况稳定</h2><p>有 3 个报修单待处理、2 场赛事正在报名、8 件商品库存偏低。</p></div><button onClick={()=>go('notices')}><Plus/>发布消息</button></section><div className="metric-grid">{[['认证学员','286','+12 本月'],['课程收入','¥48,620','+18.2%'],['商城订单','126','本月'],['待处理报修','3','需及时处理']].map((m,i)=><article key={m[0]}><span>{m[0]}</span><strong>{m[1]}</strong><small className={i===3?'warn':''}>{m[2]}</small></article>)}</div><div className="admin-grid"><section className="admin-card"><div className="admin-card-head"><div><h3>近 7 日经营数据</h3><p>课程、商城与赛事收入</p></div><b>¥18,460</b></div><div className="bars">{[42,58,48,76,62,88,70].map((x,i)=><i key={i} style={{height:x+'%'}}><span>{['四','五','六','日','一','二','三'][i]}</span></i>)}</div></section><section className="admin-card"><div className="admin-card-head"><div><h3>今日待办</h3><p>按优先级处理</p></div></div><div className="todos">{[['处理 3 个新报修单','repairs'],['审核 1 条飞友动态','community'],['确认秋季赛报名名单','events'],['补充 8 件低库存商品','products']].map(([x,v],i)=><button key={x} onClick={()=>go(v as View)}><em>{i+1}</em><span>{x}</span><ChevronRight/></button>)}</div></section></div><section className="admin-card"><div className="admin-card-head"><div><h3>最近动态</h3><p>全业务实时记录</p></div><button>查看全部</button></div><div className="activity">{[['课程购买','林小飞购买「飞手系统班」','¥699 · 10分钟前'],['装备订单','王子墨购买竞赛级高响应球机','¥1,299 · 24分钟前'],['赛事报名','张可欣报名秋季青少年 3v3 对抗赛','报名成功 · 38分钟前'],['报修提交','陈一航提交保护罩断裂报修','待收件 · 1小时前']].map(x=><div key={x[1]}><i/><b>{x[0]}</b><span>{x[1]}</span><small>{x[2]}</small></div>)}</div></section></div>}

function Notices({say}:{say:(s:string)=>void}){return <div className="admin-grid notice-grid"><section className="admin-card admin-form"><div className="admin-card-head"><div><h3>发布机构消息</h3><p>将同步发送到学员工作台通知中心</p></div></div><label>消息标题<input placeholder="例如：周六训练时间调整"/></label><label>发送对象<select><option>全部学员</option><option>指定班级</option><option>赛事报名学员</option><option>课程购买学员</option></select></label><label>消息内容<textarea placeholder="填写具体安排、时间、地点和注意事项"/></label><div className="form-actions"><button onClick={()=>say('草稿已保存')}>保存草稿</button><button onClick={()=>say('消息已发布并推送给学员')}>立即发布</button></div></section><section className="admin-card"><div className="admin-card-head"><div><h3>最近发布</h3><p>共 26 条消息</p></div></div><div className="publish-list">{[['秋季赛报名进入最后 10 天','全部学员','已送达 276 人'],['周六进阶班训练时间调整','周六进阶班','已送达 32 人'],['等级考核器材检查通知','考核报名学员','已送达 22 人']].map(x=><article key={x[0]}><Bell/><div><b>{x[0]}</b><span>{x[1]} · {x[2]}</span></div><button>详情</button></article>)}</div></section></div>}

function Manager({view,say}:{view:Exclude<View,'overview'|'notices'|'settings'>,say:(s:string)=>void}){const config:any={repairs:['报修工单',['工单号','学员','故障描述','进度','提交时间'],'新建线下工单'],events:['赛事列表',['赛事名称','比赛日期','报名人数','状态'],'发布赛事'],products:['商品与库存',['商品名称','分类','价格','库存','状态'],'新增商品'],orders:['装备订单',['订单号','学员账号','商品','金额','状态'],'导出订单'],courses:['课程与购买',['课程名称','课时','已购人数','售价','状态'],'新增课程'],students:['学员账号',['账号','姓名','所在班级','已购课程','状态'],'新增学员'],community:['社区内容审核',['发布者','内容类型','发布时间','审核状态'],'批量审核']};const [title,heads,action]=config[view];return <div className="admin-stack"><div className="manager-tools"><div className="admin-search"><Search/><input placeholder={'搜索'+title}/></div><button onClick={()=>say(action+'功能已打开')}><Plus/>{action}</button></div><section className="admin-card table-card"><div className="admin-card-head"><div><h3>{title}</h3><p>数据与学员端实时对应</p></div><div className="filter-pills"><button className="on">全部</button><button>待处理</button><button>已完成</button></div></div><div className="admin-table"><div className="tr head">{heads.map((h:string)=><span key={h}>{h}</span>)}<span>操作</span></div>{(rows as any)[view].map((r:string[],i:number)=><div className="tr" key={r[0]}>{r.map((x,j)=><span key={x} className={j===r.length-1?'status':''}>{x}</span>)}<span><button onClick={()=>say('已打开 '+r[0]+' 的详情')}>查看 / 编辑</button></span></div>)}</div></section>{view==='repairs'&&<section className="admin-card repair-note"><Wrench/><div><b>维修流程</b><p>收到学员报修后，可依次更新：已收件 → 检测中 → 待确认 → 维修完成，进度会自动显示在学员账号中。</p></div></section>}</div>}

function SettingsPage({say}:{say:(s:string)=>void}){return <div className="admin-grid"><section className="admin-card admin-form"><h3>机构资料</h3><label>机构名称<input defaultValue="SBS 无人机足球中心"/></label><label>联系电话<input defaultValue="400-800-SBS"/></label><label>工作台公告<textarea defaultValue="专注青少年无人机足球训练、竞赛与装备服务。"/></label><button className="primary" onClick={()=>say('机构资料已保存')}>保存设置</button></section><section className="admin-card"><h3>后台权限</h3><div className="permission">{[['超级管理员','全部权限'],['教练账号','课程、赛事与学员'],['维修人员','仅报修工单'],['商城人员','商品与订单']].map(x=><div key={x[0]}><b>{x[0]}</b><span>{x[1]}</span><button>配置</button></div>)}</div></section></div>}
